export const ADD_LAMP_POST = 'ADD_LAMP_POST';
export const REMOVE_LAMP_POST = 'REMOVE_LAMP_POST';
export const FLAG_REMOVING_LAMP_POST = 'FLAG_REMOVING_LAMP_POST';
export const RESIZE_LAMP_POST = 'RESIZE_LAMP_POST';
export const CHANGE_LAMP_POST_SHIELDING = 'CHANGE_LAMP_POST_SHIELDING';
